from pynput.mouse import Button, Controller
import time

mouse = Controller()
time.sleep(5)
def autoReport():
    mouse.position = (999, 185) # 3 dots
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (779, 449) # Report
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (640, 520) # Report Account
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (732, 424) # It's posting content that shouldn't be on Instagram
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (728, 526) # Violence or dangerous organizations
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (745, 466) # Dangerous organizations or individuals
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (760, 714) # Submit Report
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (750, 620) # Close
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(2) # Mini Break
    mouse.position = (999, 185) # 3 dots
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (779, 449) # Report
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (640, 520) # Report Account
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (721, 478) # It's pretending to be someone else
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (700, 360) # Me
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (760, 714) # Submit Report
    mouse.press(Button.left)
    mouse.release(Button.left)
    time.sleep(1)
    mouse.position = (750, 620) # Close
    mouse.press(Button.left)
    mouse.release(Button.left)

autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
autoReport()
time.sleep(2)
